name: Go

on:
  push:
    branches: [$default-branch]
  paths-ignore:
    - README.md
    - CHANGES.md
    - .github/**
    - .gitignore
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"
          # caching dependencies is enabled by default using the setup-go action

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
